<h1>Python básico - Ejercicios cortos (4 puntos)</h1>

En este primer notebook, puedes encontrar el enunciado de cinco ejercicios cortos a los que deberás dar solución en una única celda de código. En los casos en los que se pida una función, se debe incluir un ejemplo de llamada a la función creada.

### 1. Escribe una comprensión de lista que a partir de una lista de números genere otra con los números de la original que verifican las tres condiciones siguientes: 


- Son positivos. 
- Son divisibles por 7. 
- No son múltiplos de 2.</h3>

In [1]:
def funcion(lista):
    cumplen = [element for element in lista if element > 0 and element%7 == 0 and element%2 != 0]
    return cumplen

In [2]:
lista = [1, 20, 14, 7, 21, 33, 12, 7, 15]

funcion(lista)

[7, 21, 7]

### 2. Crea una función que reciba como _input_ una lista y devuelva una tupla (valor, cantidad de repeticiones), donde la cantidad de repeticiones es el número de veces consecutivas que aparece el valor.

Por ejemplo, empaquetar ([1, 1, 1, 3, 5, 1, 1, 3, 3]) debe devolver [(1, 3) , (3, 1) , (5, 1), (1, 2), (3, 2)].

**Observación:** La lista no tiene por qué ser sólo de números.

In [3]:
def funcion_2(lista):
    
    nueva_lista = []
    
    reps = 0 
    
    for i in range(len(lista)):
      
        if i == 0:
            
            next
            
        else:  
            if i == len(lista) - 1: #es decir, si la posición i es la última posición:
                if lista[i] == lista[i - 1]: #si es igual que la anterior:
                    reps += 1 
                    tupla = (lista[i], reps + 1) #le ponemos reps + 1 porque está repetido 2 veces, en i y en i-1 son el mismo valor. 
                    nueva_lista.append(tupla)

                elif lista[i] != lista[i - 1]: #si no son iguales, solo se repite una vez (él mismo)
                    tupla = (lista[i], 1)
                    nueva_lista.append(tupla)
                    reps = 0 #volvemos a poner reps en 0, ya que no se repite.
                    
            else: #para todos los demás casos (ni el primer elemento ni el último)
            
                if lista[i] == lista[i - 1]:
                    reps += 1 #le sumamos repeticiones pero todavía no lo metemos en la lista, ya que podría repetirse más veces.

                elif lista[i] != lista[i - 1]: #cuando nos encontramos con un elemento diferente del anterior:
                    tupla = (lista[i - 1], reps + 1) #le añadimos el elemento anterior con sus repeticiones. 
                    nueva_lista.append(tupla)
                    reps = 0 #volvemos a poner las repeticiones a 0.
                    
    return nueva_lista        

In [4]:
lista = [1, 1, 1, 3, 5, 1, 1]

funcion_2(lista) #aqui vemos que funciona con una lista de números.

[(1, 3), (3, 1), (5, 1), (1, 2)]

In [5]:
lista2 = ["a", "b", "c", "d", "e", "f", "g", "h", "h", "h"]

In [6]:
funcion_2(lista2) #y aqui se puede apreciar que también funciona con una lista de caracteres.

[('a', 1),
 ('b', 1),
 ('c', 1),
 ('d', 1),
 ('e', 1),
 ('f', 1),
 ('g', 1),
 ('h', 3)]

### 3.  Crea una función que tome como parámetros el nombre de una ciudad y un diccionario con nombres de personas y la ciudad en la que vive y devuelva los nombres de personas que viven en esa ciudad, en orden alfabético.   

Ejemplo de diccionario: {Antonio: Valladolid, Ana: Soria, Juan: Alicante, Rafael: Córdoba, Arturo: Madrid, Carmen: Granada,Delia: Alicante, Miguel: Soria, Marta : Alicante}

In [7]:
def funcion3(nombre_ciudad, diccionario_personas):
    
    nombres = []
    
    for key in diccionario_personas.keys():
        
        ciudad = diccionario_personas[key] #la ciudad en la que vive cada persona del diccionario sobre el que vamos iterando en función de las llaves.
        
        if ciudad == nombre_ciudad:
            
            nombres.append(str(key))
            print(nombres) #en cada iteración en que se cumpla la condición, le pedimos que nos devuelva la lista completa que ha ido creando y el nuevo elemento que ha añadido. 
            print(key)
        
        else:
            next
            
    nombres = sorted(nombres) #finalmente los ordenamos alfabéticamente. 
    return nombres 

In [8]:
dic = {"Andrea": "Valencia", "Borges": "Valencia", "Carlos": "Madrid", "Alicia": "Valencia"}

In [9]:
nombres = funcion3("Valencia", dic)
nombres

['Andrea']
Andrea
['Andrea', 'Borges']
Borges
['Andrea', 'Borges', 'Alicia']
Alicia


['Alicia', 'Andrea', 'Borges']

### 4. Escribe una función que reciba un nombre de fichero, lo abra y devuelva un diccionario con las palabras (asume que están separadas siempre por espacios) del fichero y sus frecuencias. Se deberá controlar la posibilidad de que el fichero no exista.

In [10]:
import numpy as np

In [11]:
def funcion4(fichero):
    
    import os
    
    from collections import Counter #importamos estos dos módulos dentro de la función porque solo van a ser usados si se utiliza esta función. 
    
    if (fichero in os.listdir()): #si el fichero que le hemos pasado existe en el directorio: 

        print("El fichero existe; Estoy trabajando")
        
        with open(fichero, "r") as f:
            
            cnt = Counter()
            
            contenido = f.read().split(' ')

            for palabra in contenido:

                cnt[palabra] += 1 #con esto nos creamos una estructura similar a un diccionario (aunque luego habrá que transformarla a dict), en el que las palabras, asumiendo que están separadas por espacios, serán las keys, y los valores serán el número de repeticiones que aparece cada palabra en el fichero. 
            
            f.close()  #cuando acabe de cargarse el contador cnt (es decir, cuando se haya leído todo el contenido), se cierra el fichero. 
            
            return dict(cnt)
         
    else:
        print("El nombre del fichero no se encuentra en el directorio \n Prueba con otro fichero o comprueba tu directorio")
        

In [12]:
fichero = "texto_prueba.txt"

dic = funcion4(fichero)



El fichero existe; Estoy trabajando


In [13]:
dic

{'Ya': 1, 'quisiera': 1, 'el': 2, 'gato': 1, 'lamer': 1, 'plato.': 1}

### 5. Escribe una función que reciba como parámetro un Sudoku completo (en forma de matriz), y devuelva si está bien solucionado o no.

A lo largo de la función, debes ir comprobando los distintos requisitos que debe cumplir la solución de un Sudoku, pero además, también debes hacer comprobaciones más básicas, como que los números de cada celda están en el rango correcto o que la dimensión de la matriz es la adecuada para un Sudoku. 

La función debe devolver un mensaje diciendo que la solución es correcta o, en caso contrario, el motivo por el que la solución es incorrecta. 

Puedes visitar esta página para repasar las reglas del Sudoku: http://www.sudokumania.com.ar/metodos/reglas-del-sudoku 


In [14]:
import numpy as np

In [15]:
matriz = np.array([[1,2,3, 4, 5, 6, 7, 8, 9], [3, 2, 1, 4, 5, 9, 8, 7, 6], 
                  [9, 8, 7, 6, 4, 5, 1, 2, 3], [6, 8, 7, 9, 1, 2, 4, 5, 3], 
                  [1,2,3, 4, 5, 6, 7, 8, 9], [6, 8, 7, 9, 1, 2, 4, 5, 3],
                  [9, 8, 7, 6, 4, 5, 1, 2, 3], [4,5,6,1,2,7,8,9, 3], 
                  [4, 2, 1, 6, 7, 9, 3, 8, 5]])

np.sum(matriz <= 9) #pequeña comprobación de que todos los elementos son menores o iguales que 9. 

81

In [16]:
matriz

array([[1, 2, 3, 4, 5, 6, 7, 8, 9],
       [3, 2, 1, 4, 5, 9, 8, 7, 6],
       [9, 8, 7, 6, 4, 5, 1, 2, 3],
       [6, 8, 7, 9, 1, 2, 4, 5, 3],
       [1, 2, 3, 4, 5, 6, 7, 8, 9],
       [6, 8, 7, 9, 1, 2, 4, 5, 3],
       [9, 8, 7, 6, 4, 5, 1, 2, 3],
       [4, 5, 6, 1, 2, 7, 8, 9, 3],
       [4, 2, 1, 6, 7, 9, 3, 8, 5]])

In [17]:
matriz.T

array([[1, 3, 9, 6, 1, 6, 9, 4, 4],
       [2, 2, 8, 8, 2, 8, 8, 5, 2],
       [3, 1, 7, 7, 3, 7, 7, 6, 1],
       [4, 4, 6, 9, 4, 9, 6, 1, 6],
       [5, 5, 4, 1, 5, 1, 4, 2, 7],
       [6, 9, 5, 2, 6, 2, 5, 7, 9],
       [7, 8, 1, 4, 7, 4, 1, 8, 3],
       [8, 7, 2, 5, 8, 5, 2, 9, 8],
       [9, 6, 3, 3, 9, 3, 3, 3, 5]])

In [18]:
def comprobar_sudoku(matriz):
    
    if ((matriz > 0) & (matriz <= 9)).all(): #asi comprobamos que todos los elementos estan entre 1 y 9. Primera condicion.
        
        for i in range(9): #con este for loop hacemos la comprobación de las filas. 
            
            fila = matriz[i]
            
            unico = np.unique(fila)
            
            if len(fila) == len(unico): #si la longitud de los elementos únicos es igual a la longitud de la fila, es que todos están entre 1 y 9 (incluidos, primera condición de arriba), y además no se repiten elementos en la fila i.
                
                print("en la fila " + str(i) + " no hay ningún elemento repetido")
                
            else: 
                
                print("en la fila " + str(i) + " HAY ELEMENTOS REPETIDOS; MAL HECHO")
        
        matrizT = matriz.T #transponemos la matriz para tener las columnas como filas, y realizamos la misma comprobación. 
        
        for j in range(9):
            
            col = matrizT[j]
            
            unico = np.unique(col)
            
            if len(col) == len(unico):
                
                print("en la columna  " + str(j) + " no hay ningún elemento repetido")
                
            else: 
                
                print("en la columna  " + str(j) + " HAY ELEMENTOS REPETIDOS; MAL HECHO")
            
        
        splitted = np.hsplit(matriz, 3) #realizamos una partición horizontal sobre la matriz original en 3 partes;
        
        regiones_completas = 0
        
        for x in splitted: #para cada una de esas partes que hemos dividido arriba:
            
            vsplitted = np.vsplit(x, 3) #volvemos a dividirlas en 3 partes, esta vez de forma vertical; quedándonos así con las regiones:
            
            for region in vsplitted: #sobre las que vamos iterando.
                
                if len(np.unique(region)) == 9: #si en cada región hay 9 elementos únicos, y habiéndose cumplido las condiciones de arriba, significa que el sudoku está bien hecho (si esto se cumple para todas las regiones (9), claro). 
                    
                    regiones_completas += 1 #vamos sumando las regiones completas; si llegan a 9 el sudoku estará bien hecho;
                    #sino, la función nos mandará un mensaje con la región en la que no se cumplen las normas. 
            
                else:
                    
                    print("La región " + str(region) + " NO CUMPLE LAS NORMAS")
                    
        if regiones_completas == 9:
            
            print("tu sudoku está bien entero, bien hecho!")
      
    else:
        
        print("El sudoku no está bien resuelto, los numeros no estan en el rango adecuado")

In [19]:
comprobar_sudoku(matriz) #vemos que en esta matriz ni las columnas ni las regiones cumplen las normas. 

en la fila 0 no hay ningún elemento repetido
en la fila 1 no hay ningún elemento repetido
en la fila 2 no hay ningún elemento repetido
en la fila 3 no hay ningún elemento repetido
en la fila 4 no hay ningún elemento repetido
en la fila 5 no hay ningún elemento repetido
en la fila 6 no hay ningún elemento repetido
en la fila 7 no hay ningún elemento repetido
en la fila 8 no hay ningún elemento repetido
en la columna  0 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  1 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  2 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  3 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  4 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  5 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  6 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  7 HAY ELEMENTOS REPETIDOS; MAL HECHO
en la columna  8 HAY ELEMENTOS REPETIDOS; MAL HECHO
La región [[1 2 3]
 [3 2 1]
 [9 8 7]] NO CUMPLE LAS NORMAS
La región [[6 8 7]
 [1 2 3]
 [6 8 7]] NO CUMPLE LAS NORMAS
La región

In [20]:
sudoku = np.array([[1,5,4,6,9,3,2,8,7],[6,3,2,5,7,8,9,4,1],[8,9,7,1,2,4,6,5,3],[5,1,9,8,4,7,3,2,6],[2,4,3,9,6,5,7,1,8], [7,6,8,3,1,2,4,9,5],[4,8,6,7,5,9,1,3,2],[9,7,5,2,3,1,8,6,4],[3,2,1,4,8,6,5,7,9]])

In [21]:
comprobar_sudoku(sudoku) #este, como vemos, sí que está bien hecho :) 

en la fila 0 no hay ningún elemento repetido
en la fila 1 no hay ningún elemento repetido
en la fila 2 no hay ningún elemento repetido
en la fila 3 no hay ningún elemento repetido
en la fila 4 no hay ningún elemento repetido
en la fila 5 no hay ningún elemento repetido
en la fila 6 no hay ningún elemento repetido
en la fila 7 no hay ningún elemento repetido
en la fila 8 no hay ningún elemento repetido
en la columna  0 no hay ningún elemento repetido
en la columna  1 no hay ningún elemento repetido
en la columna  2 no hay ningún elemento repetido
en la columna  3 no hay ningún elemento repetido
en la columna  4 no hay ningún elemento repetido
en la columna  5 no hay ningún elemento repetido
en la columna  6 no hay ningún elemento repetido
en la columna  7 no hay ningún elemento repetido
en la columna  8 no hay ningún elemento repetido
tu sudoku está bien entero, bien hecho!
